### PR TITLE
Add deploy badge for docs

### PR DESCRIPTION
**Pull request by pjbull**
Tried adding the badge from netlify, but seems like the badge does not accurately reflect GH Action builds. Will look in to updating with a badge that works.

The cooler part is I setup the DNS for nbautoexport.drivendata.org

### CODE REVIEW

**Comment by jayqi** [comment]
Based on my reading of [this thread](https://community.netlify.com/t/status-badge-incorrectly-shows-failing-when-deploy-is-auto-cancelled/7316), the Netlify badges will always show the wrong status. The GitHub Actions deploys are effectively manual deploys, but the badge shows the most recent deploy within Netlify CI, which was a failed one from before I turned off the automated builds.

**Comment by jayqi** [comment]
Since you're adding badges, we probably also want these:

[codecov](https://codecov.io/gh/drivendataorg/nbautoexport)
[PyPI](https://pypi.org/project/nbautoexport/)

```markdown
[![codecov](https://codecov.io/gh/drivendataorg/nbautoexport/branch/master/graph/badge.svg)](https://codecov.io/gh/drivendataorg/nbautoexport)
[![PyPI](https://img.shields.io/pypi/v/nbautoexport.svg)](https://pypi.org/project/nbautoexport/)
```

**Comment by pjbull** [comment]
updated:
image

**Comment by pjbull** [comment]
> I think the labels are redundant with the badges' text, and the empty header row looks kind of weird. It's not a position I hold strongly though—otherwise looks fine.

Agreed—it was more helpful when the docs were just a Netlify badge. Will update.

**Comment by pjbull** [comment]
image

**Pull request merged**
